# Generated by Django 5.1 on 2024-08-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='User name')),
                ('email', models.CharField(max_length=50, verbose_name='User email')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of the registration')),
            ],
        ),
    ]
