# Generated by Django 5.1 on 2024-08-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Book title')),
                ('author', models.CharField(max_length=50, verbose_name='Author of the book')),
                ('category', models.CharField(max_length=30, verbose_name='Category of the book')),
                ('publication_date', models.DateTimeField(verbose_name='Date of the publication')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='Date of the registration')),
            ],
        ),
    ]
